# fly.toml app configuration file generated for ws-talk-api on 2023-11-13T20:17:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ws-talk-api"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
